fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.24.0"
    powershell:
      repo: "puppetlabs/powershell"
      ref: "2.1.3"
  symlinks:
    mount_iso: "#{source_dir}"
